const Map<String, dynamic> stringData = {
  'career_options': {
    "summary":
        'We have designed our content to cater to all kids undergoing secondary education who are struggling to understand what combinations of subjects is the best fit for them. With the NEP in place making all bounds and restrictions in making stream based choices gone, we have categorized all the plethora of options into SEVEN SIMPLE CHOICES. Go on and explore details of each!',
    "overview":
        'These subject combinations include the exploration of scientific temper through the study of Physics, Chemistry, Mathematics, Biology, etc which fall under "STEM" (Science, Technology, Engineering, and Mathematics). These studies can lead to a plethora of career options but this particular bifurcation here focuses on options which truly involve degrees, careers and jobs that cater to sciences and their associated applications. Previously known as the rigid stream "Science", students are now free to explore STEM subjects without the mandation of not being able to study other creatively simulating options on the side.'
  },
  "Our Vision":
      "DoESL's venture NaksheKADAM is built in mind keeping the NEP and its modifications in mind, solving all queries of 9th to 12th graders in the most coundcive manner. It provides students with relevant information regarding what subjects will lead to what career paths, what are the Higher Educational Institutions for study for pursuing such studies, what are the entrance exams required, what aptitude tests are available, etc, how to access them, making it a one-stop solution for everything. NaksheKADAM is also a safespace for students to discuss their fears and for parents to raise queries. Our verified counsellors, industry experts, AI-based tests, chatbots and comprehsive technology driven solutions are here to help all children and parents with their issues.",
  "About DoESL":
      "National Educational Policy (NEP): Union cabinet paved the way for transformative reform in school and higher education system by launching the New National Education Policy (NEP) on 29th July 2020.  The policy aims to highlight new avenues for students in different subjects by increasing the choices students have in choosing their subject combinations and eventual careers. No student would be forced for any Language. Higher education will receive flexibility in subjects. There will be multiple entries and exit points with appropriate certification for higher education.",
  "New Education Policy' 20 - Transforming India":
      "National Educational Policy (NEP): Union cabinet paved the way for transformative reform in school and higher education system by launching the New National Education Policy (NEP) on 29th July 2020.  The policy aims to highlight new avenues for students in different subjects by increasing the choices students have in choosing their subject combinations and eventual careers. No student would be forced for any Language. Higher education will receive flexibility in subjects. There will be multiple entries and exit points with appropriate certification for higher education.",
};
